/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: FoxFX (https://sketchfab.com/FoxFXMD)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/razer-naga-trinity-97ad3933b62a4d0b9077d0186d3b082e
title: Razer Naga Trinity
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Mouse({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Mouse/mouse.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[2.45, 1.21, -8.14]}>
            <mesh
              geometry={nodes.razer_naga_trinity__0.geometry}
              material={materials["Scene_-_Root"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Mouse/mouse.gltf");
