/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DatSketch (https://sketchfab.com/DatSketch)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/google-pixel-6-pro-b9b58ca40c254f8dafd8370869af74fb
title: Google Pixel 6 Pro
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Phone({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Phone/phone.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.05}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Screen_Screen_0.geometry} material={materials.Screen} />
            <mesh geometry={nodes['BackBody_Back(top)_0'].geometry} material={materials.Backtop} />
            <mesh geometry={nodes['BackBody_Back(Bottom_0'].geometry} material={materials.BackBottom} />
            <mesh geometry={nodes.CircleCam_CamGray_0.geometry} material={nodes.CircleCam_CamGray_0.material} />
            <mesh geometry={nodes.Sensor2_Sensor_0.geometry} material={materials.Sensor} />
            <mesh geometry={nodes.RecCam_CamGray_0.geometry} material={nodes.RecCam_CamGray_0.material} />
            <mesh geometry={nodes.RecCam_CamGlass_0.geometry} material={nodes.RecCam_CamGlass_0.material} />
            <mesh geometry={nodes.Sensor_Sensor001_0.geometry} material={materials['Sensor.001']} />
            <mesh geometry={nodes.Flash_Flash_0.geometry} material={materials.Flash} />
            <mesh geometry={nodes.Mic_Mic2_0.geometry} material={materials.Mic2} />
            <mesh geometry={nodes.Mic_Mic_0.geometry} material={nodes.Mic_Mic_0.material} />
            <mesh geometry={nodes.Frontcam_CamGray_0.geometry} material={nodes.Frontcam_CamGray_0.material} />
            <mesh geometry={nodes.Frontcam_CamGlass_0.geometry} material={nodes.Frontcam_CamGlass_0.material} />
            <mesh geometry={nodes.Bezel_Bezel_0.geometry} material={materials.Bezel} />
            <mesh geometry={nodes.Bezel_Mic_0.geometry} material={nodes.Bezel_Mic_0.material} />
            <mesh geometry={nodes.Buttons_Frame_0.geometry} material={nodes.Buttons_Frame_0.material} />
            <mesh geometry={nodes.Lens3_Lens_0.geometry} material={nodes.Lens3_Lens_0.material} />
            <mesh geometry={nodes.CircleCam2_CamGray_0.geometry} material={nodes.CircleCam2_CamGray_0.material} />
            <mesh geometry={nodes.Lens1_Lens_0.geometry} material={nodes.Lens1_Lens_0.material} />
            <mesh geometry={nodes.Lens2_Lens_0.geometry} material={nodes.Lens2_Lens_0.material} />
            <mesh geometry={nodes.Lens_Lens_0.geometry} material={nodes.Lens_Lens_0.material} />
            <mesh geometry={nodes.BackBody001_Logo_0.geometry} material={materials.Logo} />
            <mesh geometry={nodes.Frame_Frame_0.geometry} material={nodes.Frame_Frame_0.material} />
            <mesh geometry={nodes.Frame_CamModuleBlack_0.geometry} material={materials.CamModuleBlack} />
            <mesh geometry={nodes.Frame_CamModule_0.geometry} material={materials.CamModule} />
            <mesh geometry={nodes.Frame_Mic_0.geometry} material={nodes.Frame_Mic_0.material} />
            <mesh geometry={nodes.Frame_Antennas_0.geometry} material={materials.Antennas} />
            <mesh geometry={nodes.Frame_CamGlass_0.geometry} material={nodes.Frame_CamGlass_0.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Phone/phone.gltf')
